'use strict';

export const UPDATE_SELECT_INDEX = 'UPDATE_SELECT_INDEX';

export const UPDATE_TRENDING_LANS = 'UPDATE_TRENDING_LANS';

export const UPDATE_IS_RENDERER = 'UPDATE_IS_RENDERER';

export const UPDATE_IS_RENDERER_ITEM = 'UPDATE_IS_RENDERER_ITEM';



