'use strict';

export const UPDATE_SELECT_KEY = 'UPDATE_SELECT_KEY';

export const UPDATE_TRENDING_LANS = 'UPDATE_TRENDING_LANS';

export const UPDATE_IS_RENDERER = 'UPDATE_IS_RENDERER';

export const UPDATE_IS_RENDERER_ITEM = 'UPDATE_IS_RENDERER_ITEM';

export const UPDATE_URL = 'UPDATE_URL';

export const UPDATE_THEME_FACTORY = 'UPDATE_THEME_FACTORY';



