'use strict';

export const UPDATE_ADVICE_REFSEH = 'UPDATE_ADVICE_REFSEH';
export const UPDATE_ADVICE_LIST_REFSEH = 'UPDATE_ADVICE_LIST_REFSEH';
export const UPDATE_ADVICE_DATA = 'UPDATE_ADVICE_DATA';
export const UPDATE_SCHEDUL_LIST_REFESH = 'UPDATE_SCHEDUL_LIST_REFESH';


